export const TURKEY_DATA: Record<string, string[]> = {
  'Adana': ['Seyhan', 'Çukurova', 'Sarıçam', 'Yüreğir', 'Ceyhan', 'Kozan'],
  'Adıyaman': ['Merkez', 'Kahta', 'Besni', 'Gölbaşı'],
  'Afyonkarahisar': ['Merkez', 'Sandıklı', 'Bolvadin', 'Dinar'],
  'Ağrı': ['Merkez', 'Patnos', 'Doğubayazıt', 'Diyadin'],
  'Amasya': ['Merkez', 'Merzifon', 'Suluova', 'Taşova'],
  'Ankara': ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut', 'Sincan', 'Altındağ', 'Pursaklar'],
  'Antalya': ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Alanya', 'Manavgat', 'Serik', 'Döşemealtı'],
  'Artvin': ['Merkez', 'Hopa', 'Arhavi', 'Borçka'],
  'Aydın': ['Efeler', 'Nazilli', 'Söke', 'Kuşadası', 'Didim'],
  'Balıkesir': ['Karesi', 'Altıeylül', 'Bandırma', 'Edremit', 'Ayvalık'],
  'Bilecik': ['Merkez', 'Bozüyük', 'Osmaneli'],
  'Bingöl': ['Merkez', 'Genç', 'Solhan'],
  'Bitlis': ['Merkez', 'Tatvan', 'Ahlat', 'Güroymak'],
  'Bolu': ['Merkez', 'Gerede', 'Mudurnu'],
  'Burdur': ['Merkez', 'Bucak', 'Gölhisar'],
  'Bursa': ['Osmangazi', 'Nilüfer', 'Yıldırım', 'İnegöl', 'Gemlik', 'Mudanya', 'Gürsu'],
  'Çanakkale': ['Merkez', 'Biga', 'Çan', 'Gelibolu'],
  'Çankırı': ['Merkez', 'Çerkeş', 'Ilgaz'],
  'Çorum': ['Merkez', 'Sungurlu', 'Osmancık', 'İskilip'],
  'Denizli': ['Pamukkale', 'Merkezefendi', 'Acıpayam', 'Tavas'],
  'Diyarbakır': ['Bağlar', 'Kayapınar', 'Yenişehir', 'Sur', 'Ergani', 'Bismil'],
  'Edirne': ['Merkez', 'Keşan', 'Uzunköprü'],
  'Elazığ': ['Merkez', 'Kovancılar', 'Karakoçan'],
  'Erzincan': ['Merkez', 'Tercan', 'Üzümlü'],
  'Erzurum': ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Horasan'],
  'Eskişehir': ['Odunpazarı', 'Tepebaşı', 'Sivrihisar'],
  'Gaziantep': ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye'],
  'Giresun': ['Merkez', 'Bulancak', 'Espiye', 'Görele'],
  'Gümüşhane': ['Merkez', 'Kelkit', 'Şiran'],
  'Hakkari': ['Merkez', 'Yüksekova', 'Şemdinli'],
  'Hatay': ['Antakya', 'İskenderun', 'Defne', 'Dörtyol', 'Samandağ'],
  'Isparta': ['Merkez', 'Eğirdir', 'Şarkikaraağaç'],
  'Mersin': ['Yenişehir', 'Toroslar', 'Mezitli', 'Akdeniz', 'Tarsus', 'Silifke', 'Erdemli'],
  'İstanbul': ['Arnavutköy', 'Ataşehir', 'Avcılar', 'Bağcılar', 'Bahçelievler', 'Bakırköy', 'Başakşehir', 'Bayrampaşa', 'Beşiktaş', 'Beykoz', 'Beylikdüzü', 'Beyoğlu', 'Büyükçekmece', 'Çatalca', 'Çekmeköy', 'Esenler', 'Esenyurt', 'Eyüpsultan', 'Fatih', 'Gaziosmanpaşa', 'Güngören', 'Kadıköy', 'Kağıthane', 'Kartal', 'Küçükçekmece', 'Maltepe', 'Pendik', 'Sancaktepe', 'Sarıyer', 'Silivri', 'Sultanbeyli', 'Sultangazi', 'Şile', 'Şişli', 'Tuzla', 'Ümraniye', 'Üsküdar', 'Zeytinburnu'],
  'İzmir': ['Aliağa', 'Balçova', 'Bayraklı', 'Bornova', 'Buca', 'Çiğli', 'Gaziemir', 'Güzelbahçe', 'Karabağlar', 'Karşıyaka', 'Konak', 'Narlıdere', 'Seferihisar', 'Selçuk', 'Tire', 'Torbalı', 'Urla'],
  'Kars': ['Merkez', 'Sarıkamış', 'Kağızman'],
  'Kastamonu': ['Merkez', 'Tosya', 'Taşköprü', 'İnebolu'],
  'Kayseri': ['Melikgazi', 'Kocasinan', 'Talas', 'Develi'],
  'Kırklareli': ['Merkez', 'Lüleburgaz', 'Babaeski'],
  'Kırşehir': ['Merkez', 'Kaman', 'Mucur'],
  'Kocaeli': ['İzmit', 'Gebze', 'Gölcük', 'Derince', 'Darıca', 'Körfez', 'Kartepe', 'Başiskele'],
  'Konya': ['Selçuklu', 'Meram', 'Karatay', 'Ereğli', 'Akşehir', 'Beyşehir'],
  'Kütahya': ['Merkez', 'Tavşanlı', 'Simav', 'Gediz'],
  'Malatya': ['Yeşilyurt', 'Battalgazi', 'Doğanşehir'],
  'Manisa': ['Yunusemre', 'Şehzadeler', 'Akhisar', 'Turgutlu', 'Salihli', 'Soma'],
  'Kahramanmaraş': ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin', 'Pazarcık'],
  'Mardin': ['Artuklu', 'Kızıltepe', 'Nusaybin', 'Midyat'],
  'Muğla': ['Menteşe', 'Bodrum', 'Fethiye', 'Marmaris', 'Milas', 'Dalaman'],
  'Muş': ['Merkez', 'Bulanık', 'Malazgirt'],
  'Nevşehir': ['Merkez', 'Ürgüp', 'Avanos'],
  'Niğde': ['Merkez', 'Bor', 'Çamardı'],
  'Ordu': ['Altınordu', 'Ünye', 'Fatsa'],
  'Rize': ['Merkez', 'Çayeli', 'Ardeşen', 'Pazar'],
  'Sakarya': ['Adapazarı', 'Serdivan', 'Erenler', 'Hendek', 'Akyazı', 'Sapanaca'],
  'Samsun': ['Atakum', 'İlkadım', 'Canik', 'Bafra', 'Çarşamba', 'Vezirköprü'],
  'Siirt': ['Merkez', 'Kurtalan', 'Eruh'],
  'Sinop': ['Merkez', 'Boyabat', 'Gerze', 'Ayancık'],
  'Sivas': ['Merkez', 'Şarkışla', 'Yıldızeli', 'Suşehri'],
  'Tekirdağ': ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Kapaklı', 'Ergene'],
  'Tokat': ['Merkez', 'Erbaa', 'Turhal', 'Niksar', 'Zile'],
  'Trabzon': ['Ortahisar', 'Akçaabat', 'Araklı', 'Of', 'Yomra'],
  'Tunceli': ['Merkez', 'Ovacık', 'Pertek'],
  'Şanlıurfa': ['Haliliye', 'Eyyübiye', 'Karaköprü', 'Siverek', 'Viranşehir', 'Suruç'],
  'Uşak': ['Merkez', 'Banaz', 'Eşme'],
  'Van': ['İpekyolu', 'Tuşba', 'Edremit', 'Erciş'],
  'Yozgat': ['Merkez', 'Sorgun', 'Akdağmadeni', 'Yerköy'],
  'Zonguldak': ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek'],
  'Aksaray': ['Merkez', 'Eskil', 'Ortaköy'],
  'Bayburt': ['Merkez', 'Aydıntepe', 'Demirözü'],
  'Karaman': ['Merkez', 'Ermenek', 'Kazımkarabekir'],
  'Kırıkkale': ['Merkez', 'Yahşihan', 'Bahşılı'],
  'Batman': ['Merkez', 'Kozluk', 'Sason'],
  'Şırnak': ['Merkez', 'Cizre', 'Silopi', 'İdil'],
  'Bartın': ['Merkez', 'Amasra', 'Ulus'],
  'Ardahan': ['Merkez', 'Göle', 'Çıldır'],
  'Iğdır': ['Merkez', 'Aralık', 'Tuzluca'],
  'Yalova': ['Merkez', 'Çınarcık', 'Çiftlikköy'],
  'Karabük': ['Merkez', 'Safranbolu', 'Eskipazar'],
  'Kilis': ['Merkez', 'Musabeyli', 'Elbeyli'],
  'Osmaniye': ['Merkez', 'Kadirli', 'Bahçe'],
  'Düzce': ['Merkez', 'Akçakoca', 'Kaynaşlı']
};
